CREATE USER testuser WITH PASSWORD '123456';

CREATE DATABASE test
WITH OWNER = postgres
ENCODING = 'UTF8'
TABLESPACE = pg_default
LC_COLLATE = 'ru_RU.UTF-8'
LC_CTYPE = 'ru_RU.UTF-8'
CONNECTION LIMIT = -1;
GRANT CONNECT, TEMPORARY ON DATABASE test TO PUBLIC;
GRANT ALL ON DATABASE test TO postgres;
GRANT ALL ON DATABASE test TO testuser;
